from solvers.pareto_hypernet.phn_wrappers import HypernetSolver
from solvers.pareto_mtl.pareto_mtl import ParetoMTLSolver
from solvers.single_task import SingleTaskSolver
from solvers.a_features import AFeaturesSolver